server:
  port: 2312

spring:
  application:
    name: OnlineShopping
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: Madhu#223
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: solomonraj257@gmail.com
    password: skfcwvmuzwekymmg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: false
    suffix: .html